INSERT INTO public.dicionario_fonetico (chave, tipo, variantes) VALUES
('A', 'letra', '["a", "ay", "ah", "aye", "eight"]'::jsonb),
('B', 'letra', '["b", "be", "bee"]'::jsonb),
('C', 'letra', '["c", "see", "sea", "si"]'::jsonb),
('D', 'letra', '["d", "dee", "de", "di", "thee"]'::jsonb),
('E', 'letra', '["e", "ee", "i", "he"]'::jsonb),
('F', 'letra', '["f", "ef", "eff", "if", "half"]'::jsonb),
('G', 'letra', '["g", "gee", "jee", "ji"]'::jsonb),
('H', 'letra', '["h", "aitch", "age", "eight", "each", "edge", "eitch"]'::jsonb),
('I', 'letra', '["i", "eye", "aye", "ai"]'::jsonb),
('J', 'letra', '["j", "jay", "hey", "joy"]'::jsonb),
('K', 'letra', '["k", "kay", "ok"]'::jsonb),
('L', 'letra', '["l", "el", "ell", "hell"]'::jsonb),
('M', 'letra', '["m", "em", "am"]'::jsonb),
('N', 'letra', '["n", "en", "an", "and", "in"]'::jsonb),
('O', 'letra', '["o", "oh", "owe", "zero"]'::jsonb),
('P', 'letra', '["p", "pee", "pea", "pe"]'::jsonb),
('Q', 'letra', '["q", "cue", "queue", "cute"]'::jsonb),
('R', 'letra', '["r", "are", "our", "ar", "er"]'::jsonb),
('S', 'letra', '["s", "as", "is", "yes", "ass", "es", "us"]'::jsonb),
('T', 'letra', '["t", "tea", "tee", "ti", "to"]'::jsonb),
('U', 'letra', '["u", "you", "yu", "ew"]'::jsonb),
('V', 'letra', '["v", "vee", "ve"]'::jsonb),
('W', 'letra', '["w", "double you", "double u", "double-u", "dabliu"]'::jsonb),
('X', 'letra', '["x", "ex", "axe", "ax"]'::jsonb),
('Y', 'letra', '["y", "why", "wai", "uai"]'::jsonb),
('Z', 'letra', '["z", "zee", "zed", "set"]'::jsonb),
('0', 'digito', '["0", "zero", "oh"]'::jsonb),
('1', 'digito', '["1", "one", "won"]'::jsonb),
('2', 'digito', '["2", "two", "too", "to"]'::jsonb),
('3', 'digito', '["3", "three"]'::jsonb),
('4', 'digito', '["4", "four", "for"]'::jsonb),
('5', 'digito', '["5", "five"]'::jsonb),
('6', 'digito', '["6", "six"]'::jsonb),
('7', 'digito', '["7", "seven"]'::jsonb),
('8', 'digito', '["8", "eight", "ate"]'::jsonb),
('9', 'digito', '["9", "nine"]'::jsonb),
('SPACE', 'comando', '["space", "spice", "pace", "base", "spay", "place", "blank"]'::jsonb),
('DOUBLE', 'comando', '["double", "buble", "bubble", "dabble", "bobble", "2", "two"]'::jsonb),
('AS', 'fusao_bigrama', '["as"]'::jsonb),
('IN', 'fusao_bigrama', '["in"]'::jsonb),
('OF', 'fusao_bigrama', '["of"]'::jsonb),
('M', 'confusao_acustica', '["N"]'::jsonb),
('N', 'confusao_acustica', '["M"]'::jsonb),
('B', 'confusao_acustica', '["V", "P"]'::jsonb),
('D', 'confusao_acustica', '["T"]'::jsonb);
